os: linux
  
language: go

go:
  - 1.13.x

services:
  - docker
  
script:   
  # Test the code
  - go test -v ./...
  # Build the code 
  - env GOOS=linux GOARCH=amd64 go build -o demo
  # - CGO_ENABLED=0 go build -o demo
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  
  - docker build -f Dockerfile -t evasp/demo:latest ./
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag evasp/demo:latest evasp/demo:$GIT_SHA
  
  - docker push evasp/demo:latest
  - docker push evasp/demo:$GIT_SHA